name: Translator Service 
on: [pull_request]

jobs:
  check_changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci --no-audit --no-progress --prefer-offline
      - name: Package action
        run: npm run package
      - name: Run action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
